DROP TABLE IF EXISTS answer CASCADE;
DROP TABLE IF EXISTS question CASCADE;
DROP TABLE IF EXISTS site_user CASCADE;

CREATE TABLE site_user (
    id BIGINT NOT NULL AUTO_INCREMENT,
    username VARCHAR(255),
    password VARCHAR(255),
    email VARCHAR(255),
    PRIMARY KEY (id),
    CONSTRAINT UK_username UNIQUE (username),
    CONSTRAINT UK_email UNIQUE (email)
);

CREATE TABLE question (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    subject VARCHAR(200),
    content CLOB,
    create_date TIMESTAMP,
    modify_date TIMESTAMP,
    author_id BIGINT,
    PRIMARY KEY(id),
    FOREIGN KEY (author_id) REFERENCES site_user(id)
);

CREATE TABLE answer (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    content CLOB,
    create_date TIMESTAMP,
    modify_date TIMESTAMP,
    question_id INTEGER,
    author_id BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (question_id) REFERENCES question(id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES site_user(id)
);