drop table if exists question CASCADE;

create table question (
    id integer generated by default as identity,
    subject varchar(200),
    content clob,
    create_date TIMESTAMP,
    primary key(id)
);

DROP TABLE IF EXISTS answer CASCADE;

CREATE TABLE answer (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    content     CLOB,
    create_date TIMESTAMP,
    question_id INTEGER,

    PRIMARY KEY (id),
    FOREIGN KEY (question_id) REFERENCES question(id) ON DELETE CASCADE
);